easy_admin:
    site_name: 'Kroon Admin'
    user:
        display_name: true
        display_avatar: false
    entities:
        # List the entity class name you want to manage
        - App\Entity\Comment
        - App\Entity\Post
        - App\Entity\Tag
        - App\Entity\User
