lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '2a0a76ee9a564888e5b75c2b00d29ceb'
    token_ttl: 3600
