vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /uploads/avatar
            upload_destination: '%kernel.project_dir%/Back/public/uploads/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true